[workspace]
resolver = "3"
members = []

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license = "Apache-2.0"
publish = false

[workspace.lints.rust]
unsafe_code = "deny"
warnings = "deny"
unused_results = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "warn", priority = -1 }

unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
dbg_macro = "deny"

multiple_unsafe_ops_per_block = "deny"
undocumented_unsafe_blocks = "deny"
